
import type { Genre, ArtStyle, PanelLayout } from './types';

export const GENRES: Genre[] = ["Superhero", "Sci-Fi", "Fantasy", "Horror", "Romance", "Comedy", "Slice of Life"];
export const ART_STYLES: ArtStyle[] = ["Classic American Comics", "Manga/Anime", "European Graphic Novel", "Cartoon/Animated", "Noir/Monochrome", "Indie Comics"];
export const PANEL_LAYOUTS: PanelLayout[] = ["2-panel strip", "4-panel grid", "6-panel page", "Full splash page"];

export const ART_STYLE_PROMPTS: Record<ArtStyle, string> = {
    "Classic American Comics": `Dynamic comic book panel in classic Marvel/DC style featuring [SCENE_DESCRIPTION]. Rendered with bold, clean ink lines, vibrant primary colors, dramatic lighting with strong contrast. Character in heroic pose with flowing cape/costume, muscular anatomy with comic book proportions. Background shows [SETTING] with perspective and depth. Include motion lines, impact effects, and cinematic camera angle. Style: Jim Lee, Alex Ross, or John Romita Jr. inspired artwork. High contrast shadows, saturated colors, professional comic book coloring with cel-shading effects.`,
    "Manga/Anime": `Manga-style comic panel featuring [SCENE_DESCRIPTION] with large expressive eyes, detailed hair with flowing strands, and anime facial proportions. Black and white with screentone shading patterns, speed lines for movement, and dramatic close-up composition. Background uses perspective lines and detailed architectural elements typical of Japanese comics. Include manga-specific visual effects like flower petals, sparkles, or impact stars. Style: Akira Toriyama, Naoko Takeuchi, or modern shounen manga aesthetic.`,
    "European Graphic Novel": `European graphic novel style (bande dessinée) panel of [SCENE_DESCRIPTION]. Detailed, realistic illustration with a painterly approach to color and light. Characters have realistic proportions and expressive, subtle emotions. The setting [SETTING] is rich with architectural detail and atmospheric depth. Composition is cinematic and thoughtful. Style inspired by Moebius or Enki Bilal.`,
    "Cartoon/Animated": `Cartoon-style comic panel of [SCENE_DESCRIPTION] with exaggerated expressions, simplified but appealing character designs, and bright, friendly color palette. Characters have rounded features, large eyes, and dynamic poses with squash-and-stretch principles. Background is simplified but colorful with clear silhouettes. Style reminiscent of Disney animation, Adventure Time, or Steven Universe with clean vector-art appearance.`,
    "Noir/Monochrome": `Film noir inspired comic panel of [SCENE_DESCRIPTION] with dramatic black and white contrast, heavy shadows, and moody lighting. Character rendered with realistic proportions, detailed faces showing emotion through shadow play. Urban nighttime setting [SETTING] with rain, neon signs, or street lamps creating atmospheric lighting. Style: Frank Miller's Sin City or Art Spiegelman's detailed illustration work. High contrast, chiaroscuro lighting.`,
    "Indie Comics": `Indie comic style panel of [SCENE_DESCRIPTION]. Unique, stylized artwork with a hand-drawn feel. Line work can be loose and expressive. Colors might be limited or unconventional to create a specific mood. Focus on emotional storytelling and character-centric composition over slick action. Style inspired by artists like Daniel Clowes, Adrian Tomine, or Tillie Walden.`
};
